management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info


spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true