management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: tenant-service
          uri: lb://tenant-service
          predicates:
            - Path=/api/v1/tenant/**
    kubernetes:
      discovery:
        all-namespaces: true

