management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: spring-cloud-account-k8s
          uri: lb://spring-cloud-account-k8s
          predicates:
            - Path=/account/**
    kubernetes:
      discovery:
        all-namespaces: true

